'use strict';
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
let checks=0;
function check(condition,label) { assert.ok(condition,label); checks++; }
function loadLogic(filename,names) {
  const html=fs.readFileSync(path.join(__dirname,filename),'utf8');
  const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
  check(scripts.length===1,filename+' contains one script');
  for(const script of scripts)new vm.Script(script[1],{filename});
  checks++;
  const pure=html.match(/\/\/ PURE_START([\s\S]*?)\/\/ PURE_END/)[1];
  const context=vm.createContext({Date,Set,Number,String,JSON,Math,Error});
  vm.runInContext(pure+'\nglobalThis.api={'+names.join(',')+'};',context);
  return context.api;
}
const a=loadLogic('task-a.html',['formatJson']);
check(!a.formatJson('',2).ok,'A empty input rejected');
check(!a.formatJson('   ',2).ok,'A whitespace input rejected');
check(!a.formatJson('{"a":}',2).ok,'A malformed JSON rejected');
check(a.formatJson('{"a":[1,true,null]}',2).value==='\u007b\n  "a": [\n    1,\n    true,\n    null\n  ]\n}','A nested output uses two spaces');
check(a.formatJson('{"a":1}',4).value==='\u007b\n    "a": 1\n}','A four-space formatting');
check(a.formatJson('null',2).value==='null','A null supported');
check(a.formatJson('"资料"',2).value==='"资料"','A JSON string supported');
check(a.formatJson('123',2).value==='123','A JSON number supported');
const b=loadLogic('task-b.html',['parseDate','dateLimits','availableSlots','validateBooking']);
check(b.parseDate('2026-02-30')===null,'B invalid calendar date rejected');
check(b.parseDate('2026-10-03')!==null,'B valid date accepted');
const beforeMidnight=new Date('2026-10-03T15:59:59Z');
const midnight=new Date('2026-10-03T16:00:00Z');
check(b.dateLimits(beforeMidnight).min==='2026-10-03','B Beijing day before midnight');
check(b.dateLimits(midnight).min==='2026-10-04','B Beijing day after midnight');
check(b.dateLimits(beforeMidnight).max==='2026-10-16','B exactly 14 available dates');
check(b.availableSlots('2026-10-04').every(slot=>!slot.available),'B unavailable Sunday');
const monday=b.availableSlots('2026-10-05'), open=monday.find(slot=>slot.available).time, closed=monday.find(slot=>!slot.available).time;
const base={date:'2026-10-05',time:open,name:'测试同学',email:'test@example.com'};
check(b.validateBooking(base,beforeMidnight)==='','B complete booking accepted');
check(b.validateBooking({...base,time:closed},beforeMidnight).includes('时段'),'B unavailable slot rejected');
check(b.validateBooking({...base,time:''},beforeMidnight).includes('时段'),'B missing slot rejected');
check(b.validateBooking({...base,name:' '},beforeMidnight).includes('姓名'),'B whitespace name rejected');
check(b.validateBooking({...base,email:'wrong'},beforeMidnight).includes('邮箱'),'B malformed email rejected');
check(b.validateBooking({...base,date:'2026-10-17'},beforeMidnight).includes('日期'),'B out-of-range date rejected');
const c=loadLogic('task-c.html',['emptyState','expiredState','addResource','deleteResources','restoreResources','matches','validStoredState']);
let state=c.emptyState();
check(c.validStoredState(state),'C empty state valid');
state=c.addResource(state,'  第一章讲义  ','a',1000);state=c.addResource(state,'Design Notes','b',1100);state=c.addResource(state,'第三章练习','c',1200);
check(state.items[0].name==='第一章讲义','C name trimmed');
check(c.matches(state.items,'DESIGN').length===1,'C case-insensitive search');
check(c.matches(state.items,'讲义').length===1,'C Chinese search');
check(c.validStoredState(JSON.parse(JSON.stringify(state))),'C storage serialization round trip');
const first=c.deleteResources(state,['a','b'],'delete-one',2000);
check(first.count===2 && first.state.items.length===1,'C batch delete removes selected records');
check(first.state.pending[0].expiresAt===32000,'C deadline fixed at 30 seconds');
const second=c.deleteResources(first.state,['c'],'delete-two',3000);
check(second.state.pending.length===2,'C separate delete transactions retained');
const restoredSecond=c.restoreResources(second.state,'delete-two',31000);
check(restoredSecond.count===1 && restoredSecond.state.pending.length===1,'C second batch restores independently');
const restoredFirst=c.restoreResources(restoredSecond.state,'delete-one',31999);
check(restoredFirst.count===2 && restoredFirst.state.items.map(item=>item.id).join(',')==='a,b,c','C undo before deadline restores original order');
const atExpiry=c.restoreResources(second.state,'delete-one',32000);
check(atExpiry.expired && atExpiry.count===0 && atExpiry.state.items.length===0,'C undo at deadline rejected');
check(atExpiry.state.pending.length===1,'C only expired transaction purged');
check(c.expiredState(second.state,33000).pending.length===0,'C all expired undo batches purged');
check(c.restoreResources(JSON.parse(JSON.stringify(second.state)),'delete-one',32001).expired,'C reload cannot reset undo deadline');
check(!c.validStoredState({...state,items:[...state.items,state.items[0]]}),'C duplicate stored IDs rejected');
check(!c.validStoredState({...state,nextOrder:1}),'C invalid ordering data rejected');
assert.throws(()=>c.addResource(state,' ','d',1000));checks++;
assert.throws(()=>c.addResource(state,'a'.repeat(81),'d',1000));checks++;
console.log('Passed '+checks+' checks: inline JavaScript syntax and pure logic only. No browser checks performed.');
