const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
function harness(){const e={},pending=[],objects=new Map(),downloads=[];let serial=0;
for(const id of ['file','quality','value','download','status','previews','result','original','before','after'])e[id]={value:id==='quality'?'80':'',files:[],disabled:id==='download',hidden:id==='previews',textContent:'',listeners:{},addEventListener(type,fn){this.listeners[type]=fn},removeAttribute(key){delete this[key]}};
const document={getElementById:id=>e[id],body:{append(){}},createElement(tag){if(tag==='a')return {click(){downloads.push({name:this.download,output:objects.get(this.href)})},remove(){}};return {getContext:()=>({fillRect(){},drawImage(img){this.img=img}}),toBlob(cb,type,quality){pending.push({cb,type,quality})}}}};
vm.runInNewContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],{document,URL:{createObjectURL(o){const url='blob:'+ ++serial;objects.set(url,o);return url},revokeObjectURL(url){objects.delete(url)}},Image:class{width=100; height=100; naturalWidth=100;naturalHeight=100;async decode(){if(objects.get(this.src)?.bad)throw Error()}}});
return {e,pending,downloads,async startFile(name='old.png',bad=false){e.file.files=[{name,type:'image/png',size:10000,bad}];const p=e.file.listeners.change();await Promise.resolve();await Promise.resolve();return {p}},quality(value){e.quality.value=String(value);e.quality.listeners.input()},async complete(index=0,fail=false){const task=pending.splice(index,1)[0];task.cb(fail?null:{size:task.quality*10000,type:task.type,encodedQuality:task.quality});await Promise.resolve();await Promise.resolve()},snapshot(){e.download.listeners.click();return {quality:e.quality.value,downloadEnabled:!e.download.disabled,status:e.status.textContent,after:e.after.textContent,resultURL:e.result.src||null,lastDownload:downloads.at(-1)||null}}};}
(async()=>{const results=[];
{const h=harness(),job=await h.startFile();h.quality(20);await h.complete(0);const stale=h.snapshot();await h.complete(0);await job.p;const latest=h.snapshot();results.push({case:'quality-change-during-encoding',stale,latest,pass:!stale.downloadEnabled&&latest.lastDownload.output.encodedQuality===0.2})}
{const h=harness(),job=await h.startFile();await h.complete();await job.p;h.quality(10);const pending=h.snapshot();await h.complete();const done=h.snapshot();results.push({case:'quality-change-after-completion',pending,done,pass:!pending.downloadEnabled&&pending.after===''&&pending.status==='正在压缩…'&&done.lastDownload.output.encodedQuality===0.1})}
{const h=harness(),first=await h.startFile();const second=await h.startFile('new.png');await h.complete(0);const stale=h.snapshot();await h.complete();await Promise.all([first.p,second.p]);const done=h.snapshot();results.push({case:'file-change-during-encoding',stale,done,pass:!stale.downloadEnabled&&done.lastDownload.name==='new-compressed.jpg'})}
{const h=harness(),job=await h.startFile();await h.complete(0,true);await job.p;const failed=h.snapshot();h.quality(60);const retryPending=h.snapshot();await h.complete();const recovered=h.snapshot();results.push({case:'encoding-failure-and-quality-retry',failed,retryPending,recovered,pass:!failed.downloadEnabled&&failed.status.includes('压缩失败')&&recovered.downloadEnabled&&recovered.lastDownload.output.encodedQuality===0.6})}
{const h=harness(),job=await h.startFile();await h.complete();await job.p;const invalid=await h.startFile('bad.png',true);await invalid.p;const failed=h.snapshot();const next=await h.startFile('retry.png');await h.complete();await next.p;const recovered=h.snapshot();results.push({case:'invalid-file-and-file-retry',failed,recovered,pass:!failed.downloadEnabled&&failed.status.includes('无法读取')&&recovered.downloadEnabled&&recovered.lastDownload.name==='retry-compressed.jpg'})}
const report={input:'index.html',inputSHA256:crypto.createHash('sha256').update(html).digest('hex'),testType:'Node VM minimal DOM/Canvas stubs, not browser',allPassed:results.every(r=>r.pass),results};fs.writeFileSync(path.join(__dirname,'logic-test-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
