const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
let count=0;
function check(name,fn){fn();count++;console.log('PASS '+name);}
function read(file){
  const html=fs.readFileSync(path.join(__dirname,file),'utf8');
  const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match=>match[1]);
  check(file+' JavaScript syntax',()=>{assert.equal(scripts.length,1);new Function(scripts[0]);});
  check(file+' unique static IDs',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length);});
  const block=scripts[0].match(/\/\* CORE_START \*\/([\s\S]*?)\/\* CORE_END \*\//)[1];
  return new Function(block+'\nreturn Core;')();
}
const A=read('task-a.html');
check('A valid object formatting',()=>assert.equal(A.format('{"a":1,"b":[true,null]}',2).text,'{\n  "a": 1,\n  "b": [\n    true,\n    null\n  ]\n}'));
check('A four-space formatting',()=>assert.equal(A.format('{"a":1}',4).text,'{\n    "a": 1\n}'));
check('A input changes produce new result',()=>assert.notEqual(A.format('{"a":1}',2).text,A.format('{"a":2}',2).text));
check('A scalars and null stay valid',()=>{for(const raw of ['null','false','0','"你好"'])assert.equal(A.format(raw,2).ok,true);});
check('A escaped strings retained',()=>assert.deepEqual(JSON.parse(A.format('{"x":"a\\nb\\\"c"}',2).text),{x:'a\nb"c'}));
check('A empty input gives next action',()=>{assert.equal(A.format('   ',2).ok,false);assert.match(A.format(' ',2).error,/粘贴/);});
check('A malformed input rejected',()=>{for(const raw of ['{"a":}','{"a":1,}','{a:1}','{"a":1} trailing'])assert.equal(A.format(raw,2).ok,false);});
check('A corrected input can retry',()=>{assert.equal(A.format('{"x":}',2).ok,false);assert.equal(A.format('{"x":1}',2).ok,true);});
const B=read('task-b.html');
const monday=Date.parse('2026-10-05T00:00:00Z');
check('B Beijing date boundary',()=>{assert.equal(B.today(Date.parse('2026-10-04T15:59:59Z')),'2026-10-04');assert.equal(B.today(Date.parse('2026-10-04T16:00:00Z')),'2026-10-05');});
check('B date month boundary',()=>assert.equal(B.addDays('2026-10-31',1),'2026-11-01'));
check('B valid date bounds',()=>{assert.equal(B.dateValid('2026-10-05','2026-10-05'),true);assert.equal(B.dateValid('2026-11-04','2026-10-05'),true);assert.equal(B.dateValid('2026-11-05','2026-10-05'),false);assert.equal(B.dateValid('2026-10-04','2026-10-05'),false);});
check('B malformed dates rejected',()=>{for(const date of ['2026-02-30','bad','2026-13-01','2026-10-5'])assert.equal(B.dateValid(date,'2026-10-05'),false);});
check('B weekends have no times',()=>{assert.deepEqual(B.slots('2026-10-03',monday),[]);assert.deepEqual(B.slots('2026-10-04',monday),[]);});
check('B demo unavailable times exist',()=>assert.equal(B.slots('2026-10-05',monday).some(slot=>!slot.available&&slot.reason==='不可选'),true));
check('B elapsed same-day slots unavailable',()=>{const now=Date.parse('2026-10-05T08:00:00Z');assert.equal(B.slots('2026-10-05',now).find(slot=>slot.time==='16:00').available,false);assert.equal(B.slots('2026-10-05',now).find(slot=>slot.time==='18:00').available,true);});
const booking={date:'2026-10-05',time:'10:00',name:'小林',email:'lin@example.com'};
check('B valid booking snapshot',()=>assert.deepEqual(B.validate(booking,monday),{}));
check('B missing slot rejected',()=>assert.ok(B.validate({...booking,time:''},monday).time));
check('B unavailable slot rejected',()=>assert.ok(B.validate({...booking,time:'15:00'},monday).time));
check('B blank name rejected',()=>assert.ok(B.validate({...booking,name:'   '},monday).name));
check('B invalid email rejected',()=>{for(const email of ['','no-email','a@','a@b','a b@c.com','a@b@c.com'])assert.ok(B.validate({...booking,email},monday).email);});
check('B corrected email retries',()=>{assert.ok(B.validate({...booking,email:'bad'},monday).email);assert.deepEqual(B.validate(booking,monday),{});});
check('B changed date must revalidate time',()=>assert.ok(B.validate({...booking,date:'2026-10-10'},monday).time));
check('B prior time rechecked at submission completion',()=>assert.ok(B.validate(booking,Date.parse('2026-10-05T02:00:00Z')).time));
const C=read('task-c.html');
let state=C.empty();
check('C empty state validates',()=>assert.equal(C.check(state),state));
check('C whitespace name rejected',()=>assert.ok(C.add(state,'  ',100,'a').error));
check('C name limit checked',()=>assert.ok(C.add(state,'a'.repeat(101),100,'a').error));
check('C trimmed new material',()=>{state=C.add(state,'  第一课  ',100,'a').state;assert.equal(state.materials[0].name,'第一课');});
check('C duplicate active name rejected',()=>assert.ok(C.add(state,'第一课',101,'b').error));
check('C prepend later material',()=>{state=C.add(state,'English notes',200,'b').state;assert.deepEqual(state.materials.map(item=>item.id),['b','a']);});
check('C search case and trim',()=>assert.deepEqual(C.visible(state,'  ENGLISH  ').map(item=>item.id),['b']));
check('C no-match search',()=>assert.deepEqual(C.visible(state,'未找到'),[]));
check('C bulk removes selected only',()=>{const result=C.remove(state,['a','missing'],1000,'tx');assert.equal(result.count,1);assert.deepEqual(result.state.materials.map(item=>item.id),['b']);assert.equal(result.state.pending[0].expiresAt,31000);});
const deleted=C.remove(state,['a','b'],1000,'tx').state;
check('C pending deletion persists in JSON',()=>assert.deepEqual(C.check(JSON.parse(JSON.stringify(deleted))),deleted));
check('C undo at 29.999 seconds restores',()=>{const result=C.undo(deleted,'tx',30999);assert.equal(result.count,2);assert.equal(result.status,'restored');assert.deepEqual(result.state.materials.map(item=>item.id),['b','a']);assert.equal(result.state.pending.length,0);});
check('C exact 30-second boundary rejects restoration',()=>{const result=C.undo(deleted,'tx',31000);assert.equal(result.status,'expired');assert.equal(result.count,0);assert.equal(result.state.materials.length,0);assert.equal(result.state.pending.length,0);});
check('C expiry counts only unrestored materials',()=>{const result=C.expire(deleted,31000);assert.equal(result.count,2);assert.equal(result.state.pending.length,0);assert.equal(result.state.materials.length,0);});
check('C double undo does not duplicate',()=>{const first=C.undo(deleted,'tx',2000);const second=C.undo(first.state,'tx',2100);assert.equal(second.status,'missing');assert.equal(second.state.materials.length,2);});
check('C missing selection makes no transaction',()=>{const result=C.remove(state,['missing'],1000,'tx');assert.equal(result.count,0);assert.equal(result.state.pending.length,0);});
check('C independent deletion deadlines',()=>{let multi=C.remove(state,['a'],1000,'t1').state;multi=C.remove(multi,['b'],11000,'t2').state;const expired=C.expire(multi,31000);assert.equal(expired.count,1);assert.equal(expired.state.pending[0].id,'t2');const restored=C.undo(expired.state,'t2',31000);assert.equal(restored.count,1);assert.deepEqual(restored.state.materials.map(item=>item.id),['b']);});
check('C corrupted persisted data rejected',()=>{for(const value of [{},null,{version:1,materials:[{id:'a',name:'x',createdAt:0},{id:'a',name:'y',createdAt:1}],pending:[]}])assert.throws(()=>C.check(value));});
console.log('Completed '+count+' checks. Browser UI and clipboard were not exercised by this script.');
