'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('assert');
let checks = 0;
function test(name, body) {body(); checks++; console.log('PASS ' + name);}
function equal(actual, expected) {assert.strictEqual(JSON.stringify(actual),JSON.stringify(expected));}
function load(name, exports) {
  const html = fs.readFileSync(path.join(__dirname,name),'utf8');
  const match = html.match(/<script>([\s\S]*?)<\/script>/);
  assert(match,'inline script exists');
  const script = match[1];
  test(name + ' JavaScript syntax',() => new Function(script));
  test(name + ' no remote assets or requests',() => {assert(!/(?:src|href)\s*=\s*["']https?:/i.test(html)); assert(!/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/.test(script));});
  const pure = script.split('// 界面逻辑')[0];
  const context = vm.createContext({Date,Intl});
  vm.runInContext(pure + '\nglobalThis.logic = {' + exports.join(',') + '};',context);
  return context.logic;
}
const a = load('task-a.html',['formatJson']);
test('A formats objects with two spaces',() => {const result = a.formatJson('{"a":1,"课程":[true,null]}','2'); assert(result.ok); equal(JSON.parse(result.text),{a:1,课程:[true,null]}); assert(result.text.includes('\n  "a"'));});
test('A formats with four spaces',() => {assert(a.formatJson('{"a":1}','4').text.includes('\n    "a"'));});
test('A formats tabs',() => {assert(a.formatJson('{"a":1}','tab').text.includes('\n\t"a"'));});
test('A supports arrays and all primitive JSON values',() => {for (const value of ['[]','0','false','null','"课程"']) {const result = a.formatJson(value,'2'); assert(result.ok); equal(JSON.parse(result.text),JSON.parse(value));}});
test('A rejects blank input with continuation',() => {const result = a.formatJson('  \n ','2'); assert(!result.ok && result.empty); assert(result.message.includes('粘贴'));});
test('A rejects malformed JSON and tells how to retry',() => {for (const value of ['{"a":}','{a:1}','{"a":1,}','{"a":1']) {const result = a.formatJson(value,'2'); assert(!result.ok); assert(result.message.includes('再点'));}});
test('A error retry accepts corrected input',() => {assert(!a.formatJson('{"a":}','2').ok); assert(a.formatJson('{"a":2}','2').ok);});
test('A does not execute pasted code',() => {assert(!a.formatJson('alert("hi")','2').ok);});
const b = load('task-b.html',['getAvailability','shiftDate','slotEnd','beijingToday']);
const min = '2026-10-04', max = '2026-10-31';
test('B exposes no slots on Sunday',() => {equal(b.getAvailability('2026-10-04',min,max),{valid:true,slots:[]});});
test('B exposes two Saturday slots',() => {equal(b.getAvailability('2026-10-10',min,max).slots,['10:00','11:00']);});
test('B weekdays have selectable times',() => {assert(b.getAvailability('2026-10-05',min,max).slots.length > 0);});
test('B invalid and out-of-range dates have no slots',() => {for (const date of ['','2026-13-04','2026-02-30','2026-10-03','2026-11-01','04/10/2026']) {equal(b.getAvailability(date,min,max),{valid:false,slots:[]});}});
test('B date range retains valid last day',() => {assert(b.getAvailability(max,min,max).valid);});
test('B date shift spans months and leap years',() => {assert.strictEqual(b.shiftDate('2026-10-31',1),'2026-11-01'); assert.strictEqual(b.shiftDate('2028-02-28',1),'2028-02-29');});
test('B each booking ends after 45 minutes',() => {assert.strictEqual(b.slotEnd('09:00'),'09:45'); assert.strictEqual(b.slotEnd('10:30'),'11:15');});
test('B current Beijing date has ISO date shape',() => {assert(/^\d{4}-\d{2}-\d{2}$/.test(b.beijingToday()));});
const c = load('task-c.html',['emptyState','parseSavedState','pruneState','addResource','deleteResources','restoreBatch']);
const t = 100000;
let initial = c.emptyState();
initial = c.addResource(initial,' 第一课 ','a',t).state;
initial = c.addResource(initial,'练习册','b',t + 1).state;
initial = c.addResource(initial,'参考资料','c',t + 2).state;
test('C adds trimmed resource names',() => {assert.strictEqual(initial.items[0].name,'第一课');});
test('C rejects blank or overly long names',() => {assert.throws(() => c.addResource(initial,'   ','d',t)); assert.throws(() => c.addResource(initial,'a'.repeat(121),'d',t));});
const first = c.deleteResources(initial,['a','b','unknown'],'batch1',t + 10);
test('C bulk deletion counts actual matched records',() => {assert.strictEqual(first.removed,2); equal(first.state.items.map(item => item.id),['c']);});
test('C deletion does not mutate input state',() => {assert.strictEqual(initial.items.length,3); assert.strictEqual(initial.undo.length,0);});
test('C each undo deadline is exactly 30 seconds',() => {assert.strictEqual(first.state.undo[0].expiresAt,t + 30010);});
test('C restores before deadline with exact count',() => {const result = c.restoreBatch(first.state,'batch1',t + 30009); assert(result.ok); assert.strictEqual(result.restored,2); equal(result.state.items.map(item => item.id),['a','b','c']); assert.strictEqual(result.state.undo.length,0);});
test('C rejects undo at exact deadline',() => {const result = c.restoreBatch(first.state,'batch1',t + 30010); assert(!result.ok); assert.strictEqual(result.restored,0); equal(result.state.items.map(item => item.id),['c']);});
test('C rejects undo after deadline',() => {assert(!c.restoreBatch(first.state,'batch1',t + 30011).ok);});
const second = c.deleteResources(first.state,['c'],'batch2',t + 5000);
test('C repeated deletes keep independent deadlines',() => {equal(second.state.undo.map(batch => batch.expiresAt),[t + 30010,t + 35000]);});
test('C expired earlier batch does not expire later batch',() => {const result = c.restoreBatch(second.state,'batch2',t + 31000); assert(result.ok); assert.strictEqual(result.restored,1); equal(result.state.items.map(item => item.id),['c']); assert.strictEqual(result.state.undo.length,0);});
test('C reload retains unexpired undo data',() => {const reloaded = c.parseSavedState(JSON.stringify(first.state)); assert(c.restoreBatch(reloaded,'batch1',t + 20000).ok);});
test('C reload cannot restore expired records',() => {const reloaded = c.parseSavedState(JSON.stringify(first.state)); const pruned = c.pruneState(reloaded,t + 30010); assert.strictEqual(pruned.undo.length,0); assert(!c.restoreBatch(pruned,'batch1',t + 30010).ok);});
test('C undo preserves additions made after deletion',() => {const added = c.addResource(first.state,'新增资料','d',t + 100).state; const result = c.restoreBatch(added,'batch1',t + 200); equal(result.state.items.map(item => item.id),['a','b','c','d']);});
test('C duplicate restored IDs do not inflate restored count',() => {const state = JSON.parse(JSON.stringify(first.state)); state.items.push(initial.items[0]); const result = c.restoreBatch(state,'batch1',t + 100); assert.strictEqual(result.restored,1); assert.strictEqual(result.state.items.length,3);});
test('C nonexistent selection makes no undo batch',() => {const result = c.deleteResources(initial,['unknown'],'none',t + 50); assert.strictEqual(result.removed,0); assert.strictEqual(result.state.undo.length,0);});
test('C invalid stored data is rejected',() => {assert.throws(() => c.parseSavedState('{broken')); assert.throws(() => c.parseSavedState('{"version":1,"items":[{}],"undo":[]}'));});
test('C storage round trip preserves names and times',() => {equal(c.parseSavedState(JSON.stringify(second.state)),second.state);});
console.log('TOTAL ' + checks + ' passed. Scope: syntax and pure functions only; no browser verification.');
